### ISSUE TITLE
nk_cancelLoading() seems not working thoroughly when scrolling fast in a table view

### ISSUE THREAD

**Issue by joe528** [kean/Nuke#59]
Let's say I have a table view with 1000 cells where each cell downloads one image in `willDisplayCell`:

    cell.image.nk_setImageWith(...)

and each row cancels image in `didEndDisplayingCell`:

    cell.image.nk_cancelLoading()

It works pretty well except the case when I scroll very fast (as fast as I can).

Why do I say `nk_cancelLoading` not working "thoroughly"?

- NOT Working -> When I scroll fast, say from row 1 to row 500, and I stop at row 500, the cells around row 500 shows no image until 10-20 seconds (seems waiting for something to be finished).
- Working -> After I see the images for the rows around row 500, and if I scroll back, I see no images are downloaded for earlier rows (when I scroll back, images are shown in a second, which is normal if I scroll normally), which means "cancelling" is working. The images that had been cancelled wasn't downloaded.

So for the not-working case, I guess somehow, the network requests still jammed in the lower level? Or why would it take so long to show the images. If previous image requests are all cancelled without blocking current requests, the images should shown within one or two seconds as usual.

**Comment by kean** [comment]
It used to work correctly, might be something I've missed in v2.x. I'll take a look soon, thanks.

**Comment by kean** [comment]
The tasks do get cancelled, there is no problem with that. Apparently there is too much NSURLSessionTasks being resumed and cancelled, even though there is a mechanism that prevents excessive creation of tasks. I have an idea how to improve this, I'll work on it on a weekend.

**Comment by kean** [comment]
I've made some changes in the `develop` branch which I'm pretty happy with, it works as expected now. I'll test it tomorrow and release a v2.2 soon. It would be nice if you could test it too.

**Comment by joe528** [comment]
I downloaded `develop` branch (only one file different: ImageLoader.swift from my SVN diff)

I cleaned up & re-built. I saw hundreds of logs like this in the console:

`execute <__NSCFLocalDataTask: 0x138ec2e60>{ taskIdentifier: 441 } { running }, pending: 0, executing: 7
execute <__NSCFLocalDataTask: 0x1390042d0>{ taskIdentifier: 442 } { running }, pending: 0, executing: 6
execute <__NSCFLocalDataTask: 0x138d67a20>{ taskIdentifier: 443 } { running }, pending: 0, executing: 4
execute <__NSCFLocalDataTask: 0x138dec600>{ taskIdentifier: 444 } { running }, pending: 0, executing: 5
execute <__NSCFLocalDataTask: 0x138daae20>{ taskIdentifier: 445 } { running }, pending: 0, executing: 6
execute <__NSCFLocalDataTask: 0x138dab090>{ taskIdentifier: 446 } { running }, pending: 0, executing: 7
execute <__NSCFLocalDataTask: 0x138ede9d0>{ taskIdentifier: 447 } { running }, pending: 0, executing: 6
execute <__NSCFLocalDataTask: 0x138ec2e60>{ taskIdentifier: 448 } { running }, pending: 0, executing: 7
execute <__NSCFLocalDataTask: 0x1390042d0>{ taskIdentifier: 449 } { running }, pending: 0, executing: 7
execute <__NSCFLocalDataTask: 0x137734180>{ taskIdentifier: 450 } { running }, pending: 0, executing: 4
execute <__NSCFLocalDataTask: 0x138962030>{ taskIdentifier: 451 } { running }, pending: 0, executing: 5
execute <__NSCFLocalDataTask: 0x138c57520>{ taskIdentifier: 452 } { running }, pending: 0, executing: 4
execute <__NSCFLocalDataTask: 0x138c225e0>{ taskIdentifier: 453 } { running }, pending: 0, executing: 5
execute <__NSCFLocalDataTask: 0x138c22920>{ taskIdentifier: 454 } { running }, pending: 0, executing: 6
execute <__NSCFLocalDataTask: 0x138c57240>{ taskIdentifier: 455 } { running }, pending: 0, executing: 7`

However, the testing result is the same. I still have to wait 10-20+ seconds before I start to see images. Probably you should try to scroll faster? If I don't scroll fast enough, the images come up without problem. But if I keep accelerating the scrolling (keep moving the finger until the images stop catching up), the problem can be seen.

**Comment by joe528** [comment]
By the way, I call `ImageManager.shared.removeAllCachedImages()` before a testing.

**Comment by kean** [comment]
I'm testing it in a `nk59-test` branch. I've tried multiple configurations: 

- Disable task reusing in `ImageLoader`
- Disable disk storage
- Disable memory storage

It works just fine, and I do scroll fast enough (see taskIdentifiers):

```
execute <__NSCFLocalDataTask: 0x14a81a3e0>{ taskIdentifier: 31248 } { running }, pending: 3, executing: 10
execute <__NSCFLocalDataTask: 0x14a8137c0>{ taskIdentifier: 31247 } { running }, pending: 2, executing: 10
execute <__NSCFLocalDataTask: 0x14a8174c0>{ taskIdentifier: 31246 } { running }, pending: 1, executing: 10
execute <__NSCFLocalDataTask: 0x14a80c750>{ taskIdentifier: 31245 } { running }, pending: 0, executing: 10
```
However, I did find a problem with `Alamofire`. I've missed the fact that they resume `NSURLSessionTasks` right after they are created (`startRequestsImmediately` option). This behaviour defeats the purpose of limiting number of concurrent tasks in `Nuke.ImageLoader`. I'll fix this in https://github.com/kean/Nuke-Alamofire-Plugin/issues/2

Are you testing it with `Alamofire` plugin?

**Comment by kean** [comment]
https://github.com/kean/Nuke-Alamofire-Plugin/issues/2 does fixes the issue with `Alamofire`.

**Comment by joe528** [comment]
I am not sure if I am testing it with Alamofire plugin... 

I do have `pod "Alamorefire"` but I don't have `pod "Nuke-Alamofire-Plugin"` in my pod file. 

Any specific code to use Alamorefire plugin?

How to verify if I am using it?

**Comment by kean** [comment]
> Any specific code to use Alamorefire plugin?

You have to install it and then create custom `Nuke.ImageManager` with an `Nuke.AlamofireImageDataLoader`. You would have known if you use it.

Back to the issue. I've found two problems, both are fixed now. You can checkout `nk59-test` branch, update pods, and run "Basic" (built-in networking) and/or "Alamofire" (Alamofire networking) demos to see it for yourself. 

Those fixes hasn't been released yet, changes to `Nuke` are in `develop` branch, changes to `Nuke Alamofire Plugin` are in `master` branch of the corresponding repos.

If you are still experiencing any issues please either provide access to your project, or create a demo project (you can use Nuke's demo), I'll be glad to help.

**Comment by joe528** [comment]
It result is still the same. I will see if I can build a project that reproduce it so that you can see it too.

**Comment by joe528** [comment]
In case my own code causes the issue, I created a new project with a simple `UITableView` and a custom `UITableViewCell` that contains only one `UIImageView` & one `UILabel`. (The project is attached with this message)

Fortunately, the problem can be reproduced with this simple project. But there is one thing about the scrolling speed, I have to scroll "at a certain speed" to reproduce the problem.

- Too slow: of course, images are downloaded without problem.
- Too fast: as you can see the text "item # N", certain items (cells) are plainly ignored by iOS itself (without any attempt to render these cells). Therefore, when scrolling too fast, a lot of items (cells) are ignored (no request for image download), so the image downloading process still catches up. My original app has more complicated cell layout, therefore I guess when I scroll as fast as I can, iOS spends more time rendering each cell without ignoring cells, so it was a coincidence I was scrolling "at a certain speed" to see the problem.

I also make a video when I was trying to reproduce the problem. As you can see from the video, for the first 400 items, I was either scrolling too slow or too fast, there was no problem for the images to be downloaded and shown up. However, around row 400 or so I was scrolling at a certain speed, you can see clearly that no images are downloaded afterwards. I had to wait 10-20 seconds or sometimes even longer to see image downloading back to normal.

The video is 90MB in size. I cannot upload it, so I put it on a server temporarily: http://ibarkley.com/_tmp/nuke.mov



[NukeTestFastScrolling.zip](https://github.com/kean/Nuke/files/159730/NukeTestFastScrolling.zip)

**Comment by kean** [comment]
> I have to scroll "at a certain speed" to reproduce the problem

Yeah, that's true. Nuke 2.0...2.2 ignored requests that were cancelled in a short period of time after they were created. That was an experimental feature (that you could turn off), it didn't work as well as I expected. Now `ImageLoader` simply limits number of concurrent NSURLSessionTasks - honestly, that's how it should've been implemented in the first place.

> The project to reproduce the problem:
> NukeTestFastScrolling.zip

You should update dependency in your podfile to, your are not seeing the changes made in `develop` branch.

```ruby
pod "Nuke", :git => "https://github.com/kean/Nuke.git", :branch => "develop"
```

I'll release those changes as soon as I finish testing it.

**Comment by joe528** [comment]
I thought all changes were in `nk59-test` so I just manually downloaded the branch and copied the source files into the project.

What you mean is that you actually had fix for the problem I am seeing?

Do you want me to do any further testing at this moment?

**Comment by kean** [comment]
> What you mean is that you actually had fix for the problem I am seeing?

Yes, it clearly is fixed.

> Do you want me to do any further testing at this moment?

I'm testing on your sample project.

First, I install Nuke from master:

```
#podfile

**Comment by joe528** [comment]
I updated `podfile` with 
`pod "Nuke", :git => "https://github.com/kean/Nuke.git", :branch => "develop"`

and run `pod update`

I still can reproduce the problem with the sample project I sent you.

**Comment by kean** [comment]
Well, I guess I'll release those changes (hard limit for number of concurrent tasks) anyway.

Once again, I've tested it using your sample project. I can clearly see a problem using Nuke version from `master` (10+ seconds delay, just like your described), and I can confirm that there is no delay in `develop` branch.

Sorry, I can't allocate any more time on this issue. However, if you'll have some more ideas regarding it, please let me know.

**Comment by kean** [comment]
I made some extra improvements in a `develop` branch.

**Comment by joe528** [comment]
Yeah, I tested with your latest `develop` branch, and I was unable to reproduce the problem I was seeing.

I think the extra improvements in `develop` are very good.

**Comment by joe528** [comment]
I tested with the `develop` branch a few times. It's harder to reproduce the problem, but at certain scrolling speed, I still can see it.

Just like you said, it should be more than enough for most cases.

**Comment by BabyAzerty** [comment]
I believe to have the same issue as joe528.
I am using 3.1.3 (with "Alamofire" bundled but not used in this case, and globally never used with Nuke)
Scrolling "fast" on a UICollectionView triggers the problem.

    //My cell
    class UserCardCell: UICollectionViewCell {
        func updateContent(user: User) {
            Nuke.taskWith(NSURL(string: url)!) { result in
                if let img = result.image {
                    self.pictureImgView.image = img
                }
            }.resume()
        }
    }

    //My collection view
    func collectionView(collectionView: UICollectionView, cellForItemAtIndexPath indexPath: NSIndexPath) -> UICollectionViewCell {
        let cell = collectionView.dequeueReusableCellWithReuseIdentifier("userCardCell", forIndexPath: indexPath) as! UserCardCell
        cell.updateContent(users[indexPath.row])
        return cell
    }

    func collectionView(collectionView: UICollectionView, didEndDisplayingCell cell: UICollectionViewCell, forItemAtIndexPath indexPath: NSIndexPath) {
        (cell as! UserCardCell).pictureImgView.nk_cancelLoading()
    }



I often get complaints from real users about this glitch.
So I don't know if this is an implementation problem on my side or if it will be corrected in the next version or if I need to change library.

**Comment by kean** [comment]
Hey @BabyAzerty,

I found that you could trigger this problem by resuming and cancelling NSURLSessionTasks at a really fast rate which would eventually trash NSURLSession. AFAIK none of the existing frameworks (AlamofireImage, HanekeSwift, Kingfisher) have a built-in solution to this problem. All they do is limit the number of concurrent NSURLSessionTasks. Nuke also does that in a form of a custom `Nuke.TaskQueue` in Nuke 3, and simple `Foundation.OperationQueue` in Nuke 4. This helps in a way but does not eliminate the problem.

I think the problem requires a custom solution on app's side. In a nutshell, you need to make sure that you don't resume and immediately cancel requests when cells go offscreen. I could think of a number of ways to achieve that. A classic solution would involve [rate-limiting](https://en.wikipedia.org/wiki/Token_bucket) image requests. I believe that that goes out of scope of Nuke or other image loading frameworks (I might be wrong on this one, I would probably rethink this for Nuke 4).

**Comment by kean** [comment]
Just checked your edit. Yeah, it was much simpler in your sample, your were not cancelling requests at all. The problem that @joe528 described here is a different one (and more intricate one, thus rate-limiting etc).

**Comment by kean** [comment]
Nuke 4 now features a Rate Limiter which solves this problem ⚡
